apiVersion: v1
data:
  config.yaml: |
    alertmanagerMain:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-nfs-storage
          resources:
            requests:
              storage: 20Gi
    prometheusK8s:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-nfs-storage
          resources:
            requests:
              storage: 80Gi
      retention: 1w
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring